workspace = { members = ["minos-cli-test"] }
[package]
name = "minos-clap"
version = "0.1.0"
edition = "2021"

[dependencies]
minos = {git = "ssh://git@github.com/jonhteper/minos.git", branch = "main"}
clap = {version = "4.5.4", features = ["derive"]}
